claim_name_app/config/routes.rb
ClaimNameApp::Application.routes.draw do

  resources :users do
    resources :baby_names
  end

end

claim_name_app/app/models/baby_name.rb
class BabyName < ActiveRecord::Base
  has_and_belongs_to_many :users

  fuzzily_searchable :name

  before_save do
    self.name = self.name.downcase
  end

  def similar_names
    names = BabyName.find_by_fuzzy_name(name).map(&:name)
    names.delete(name)
    names
  end

end

claim_name_app/app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

claim_name_app/app/models/trigram.rb
class Trigram < ActiveRecord::Base
  include Fuzzily::Model
end

claim_name_app/app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :baby_names
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed


end

claim_name_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

claim_name_app/app/controllers/baby_names_controller.rb
class BabyNamesController < ApplicationController
  def new
    @baby_name= BabyName.new(:user_ids => [params[:user_id]])
    @current_user = User.find(params[:user_id])
  end

  def create
    name = BabyName.create(baby_name_params,)
    name.update_attributes(:user_ids => params[:user_id])
    redirect_to user_path(params[:user_id])
  end


  private

    def baby_name_params
      params.require(:baby_name).permit(:name)
    end

end

claim_name_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @current_user = User.find(params[:id])
  end
end

claim_name_app/app/helpers/application_helper.rb
module ApplicationHelper
end

claim_name_app/app/helpers/baby_names_helper.rb
module BabyNamesHelper
end

claim_name_app/app/helpers/users_helper.rb
module UsersHelper
end

claim_name_app/app/views/baby_names/delete.html.haml
%h1 BabyNames#delete
%p Find me in app/views/baby_names/delete.html.haml

claim_name_app/app/views/baby_names/new.html.haml
%h1 BabyNames#new
%p Find me in app/views/baby_names/new.html.haml

= semantic_form_for [@current_user, @baby_name] do |f|
  =f.inputs do
    = f.input :name

  = f.actions do
    = f.action :submit, :as => :button

claim_name_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ClaimNameApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

claim_name_app/app/views/users/show.html.haml
%h1 Users#show
%p Find me in app/views/user/show.html.haml

%h2 #{@current_user.name}

=link_to 'New Baby Name', new_user_baby_name_path(@current_user)

%table
  %tr
    %th Baby Names
  - @current_user.baby_names.each do | baby_name|
    %tr
      %td= baby_name.name.titleize